clc;
clear;
close all;

%%

% From the Ansys model, you will need the B fields generated by each
% current source

% From the current_coefficient_calculation.m, you will need the current
% coefficients file for each channel

% You will also need the B field maps from the experiments to compare with
% the simulation, you will have to modify the code according to your
% experimental data

%% 
% This code multiplies the magnetic fields with the current source coefficients to get the final images

% Load NOVA data from simulations or your experiments
load('phantom1S_coils1-8.mat')
B_NOVA = B(:,:,31:113,31:113,19:101);

% Load the mask from Ansys HFSS simulation    
load("mask.mat", "mask3D");

% Initialize matrices 
x_dim = 83;
y_dim = 83;
z_dim = 83;
%for Ansys HFSS
Bfield3D_x = zeros(x_dim,y_dim,z_dim,14); % [phantom dimensions x, y, z, 14 current sources]    
Bfield3D_y = zeros(x_dim,y_dim,z_dim,14);
Bfield3D_z = zeros(x_dim,y_dim,z_dim,14);

Bfield3D_B1plus = zeros(x_dim,y_dim,z_dim,14,8); %contains all the B fields we obtained from Ansys [phantom dimensions x,y,z,14 current sources,channels]
Nova_B1plus = zeros(x_dim,y_dim,z_dim,8); %contains all the B fields we obtained from Nova

B1_est = zeros(8,x_dim,y_dim,z_dim); %for Ansys HFSS [channels, phantom dimensions x,y,z]
Nova_B1s = zeros(8,x_dim,y_dim,z_dim); %for NOVA

B1_combined = zeros(x_dim,y_dim,z_dim, 3, 8); % [phantom dimensions x, y, z, 3 current sources, channels]  
%% Load B field data    
    
%Reshape to 3D

for channel_for_Bfield = 1:8
    % Load Ansys HFSS fields
    load("B_asymmetric_sphere"+string(channel_for_Bfield)+".mat","B_asymmetric_sphere");
    for current_source=1:14
    
            Bfield1D_x = B_asymmetric_sphere(current_source,1:x_dim*y_dim*z_dim); 

            Bfield1D_y = B_asymmetric_sphere(current_source,x_dim*y_dim*z_dim+1:x_dim*y_dim*z_dim*2);
            Bfield1D_z = B_asymmetric_sphere(current_source,x_dim*y_dim*z_dim*2+1:x_dim*y_dim*z_dim*3);
            ind = 1;
            for x=1:x_dim
                for y=1:y_dim
                    for z=1:z_dim
                        
                        Bfield3D_x(x,y,z,current_source)=Bfield1D_x(ind);
                        Bfield3D_y(x,y,z,current_source)=Bfield1D_y(ind);
                        Bfield3D_z(x,y,z,current_source)=Bfield1D_z(ind);
    
                        ind=ind+1;
                    end
                end
            end
    
            %multiply with mask
    
            Bfield3D_x(:,:,:,current_source) = Bfield3D_x(:,:,:,current_source).*mask3D;
            Bfield3D_y(:,:,:,current_source) = Bfield3D_y(:,:,:,current_source).*mask3D;
            Bfield3D_z(:,:,:,current_source) = Bfield3D_z(:,:,:,current_source).*mask3D;
    
            %calculate B1+
            
            Bfield3D_B1plus(:,:,:,current_source,channel_for_Bfield) = (Bfield3D_x(:,:,:,current_source) + 1j*Bfield3D_y(:,:,:,current_source))/2;
    end %end of current_source loop
        
        %NOVA images
    
        Nova_Bx = squeeze(B_NOVA(channel_for_Bfield,1,:,:,:)).*mask3D;
        Nova_By = squeeze(B_NOVA(channel_for_Bfield,2,:,:,:)).*mask3D;
        Nova_Bz = squeeze(B_NOVA(channel_for_Bfield,3,:,:,:)).*mask3D;


        Nova_B1plus = (Nova_Bx + 1j*Nova_By)/2;
        Nova_B1s(channel_for_Bfield,:,:,:) = Nova_B1plus*10^6;
   
end % end of the channel loop
     
%%

% The 14 current sources are combined to form 3 current sources
for channel_to_combine = 1:8
    B1_combined(:,:,:,1,channel_to_combine) = Bfield3D_B1plus(:,:,:,1,channel_to_combine) + Bfield3D_B1plus(:,:,:,2,channel_to_combine) - Bfield3D_B1plus(:,:,:,3,channel_to_combine) - Bfield3D_B1plus(:,:,:,4,channel_to_combine);
    B1_combined(:,:,:,2,channel_to_combine) = Bfield3D_B1plus(:,:,:,8,channel_to_combine) + Bfield3D_B1plus(:,:,:,9,channel_to_combine) - Bfield3D_B1plus(:,:,:,10,channel_to_combine) - Bfield3D_B1plus(:,:,:,11,channel_to_combine);
    B1_combined(:,:,:,3,channel_to_combine) = Bfield3D_B1plus(:,:,:,5,channel_to_combine) + Bfield3D_B1plus(:,:,:,6,channel_to_combine) + Bfield3D_B1plus(:,:,:,7,channel_to_combine) + Bfield3D_B1plus(:,:,:,12,channel_to_combine) + Bfield3D_B1plus(:,:,:,13,channel_to_combine) + Bfield3D_B1plus(:,:,:,14,channel_to_combine);

end

%%  
% This part of the code calculates the final B1+ fields for each channel
% using the current coefficients calculated in
% current_coefficient_calculation.m

alpha = zeros(3,8);
B1plus_final = zeros(x_dim,y_dim,z_dim);

for channel = 1:8
    load("current_coefficients_for_channel_"+string(channel)+".mat","CC");
    for contributing_channel = 1:8
        alpha(:,contributing_channel) =  CC(1+(contributing_channel-1)*2,:).*exp(1j*deg2rad(CC(2+(contributing_channel-1)*2,:)));
    end

    for contributing_channel = 1:8
        for current_source = 1:3
            B1plus_final = B1_combined(:,:,:,current_source,contributing_channel)*alpha(current_source,contributing_channel)+B1plus_final;
        end
    
    end
    
    B1_est(channel,:,:,:) = B1plus_final*10^6;
    B1plus_final = zeros(x_dim,y_dim,z_dim);
end

%%

%Draws axial, sagittal, and coronal slices from the 3D matches and the NOVA
%results

for ch = 1:8
    figure;
    subplot(3,2,1)
    imagesc(squeeze(abs(B1_est(ch,:,:,round(z_dim/2)))))
    clim([0,1])
    colorbar
    set(gca, 'XTick', [], 'YTick', []);
    subplot(3,2,2)
    imagesc(squeeze(abs(Nova_B1s(ch,:,:,round(z_dim/2)))))
    clim([0,1])
    colorbar
    set(gca, 'XTick', [], 'YTick', []);
    subplot(3,2,3)
    imagesc(squeeze(abs(B1_est(ch,:,round(y_dim/2),:))))
    clim([0,1])
    colorbar
    set(gca, 'XTick', [], 'YTick', []);
    subplot(3,2,4)
    imagesc(squeeze(abs(Nova_B1s(ch,:,round(y_dim/2),:))))
    clim([0,1])
    colorbar
    set(gca, 'XTick', [], 'YTick', []);
    subplot(3,2,5)
    imagesc(squeeze(abs(B1_est(ch,round(x_dim/2),:,:))))
    clim([0,1])
    colorbar
    set(gca, 'XTick', [], 'YTick', []);
    subplot(3,2,6)
    imagesc(squeeze(abs(Nova_B1s(ch,round(x_dim/2),:,:))))
    clim([0,1])
    colorbar
    set(gca, 'XTick', [], 'YTick', []);
    sgtitle("Channel "+string(ch))
end


%% 
% RF Shims

% Initialize the matrices
B1_est_cp = zeros(x_dim,y_dim,z_dim);
Nova_B1s_cp = zeros(x_dim,y_dim,z_dim);

B1_est_lm_cos = zeros(x_dim,y_dim,z_dim);
Nova_B1s_lm_cos = zeros(x_dim,y_dim,z_dim);

B1_est_lm_sin = zeros(x_dim,y_dim,z_dim);
Nova_B1s_lm_sin = zeros(x_dim,y_dim,z_dim);

B1_est_zero = zeros(x_dim,y_dim,z_dim);
Nova_B1s_zero = zeros(x_dim,y_dim,z_dim);

% Calculate the RF shim scenarios
for ch = 1:8
    B1_est_cp = B1_est_cp + squeeze((B1_est(ch,:,:,:).*(exp(1j*pi*(ch-1)/4))));
    Nova_B1s_cp = Nova_B1s_cp + squeeze((Nova_B1s(ch,:,:,:).*(exp(1j*pi*(ch-1)/4))));

    B1_est_lm_cos = B1_est_lm_cos + squeeze((B1_est(ch,:,:,:).*(cos(pi*(ch-1)/4))));
    Nova_B1s_lm_cos = Nova_B1s_lm_cos + squeeze((Nova_B1s(ch,:,:,:).*(cos(pi*(ch-1)/4))));

    B1_est_lm_sin = B1_est_lm_sin + squeeze((B1_est(ch,:,:,:).*(sin(pi*(ch-1)/4))));
    Nova_B1s_lm_sin = Nova_B1s_lm_sin + squeeze((Nova_B1s(ch,:,:,:).*(sin(pi*(ch-1)/4))));

    B1_est_zero = B1_est_zero + squeeze(B1_est(ch,:,:,:));
    Nova_B1s_zero = Nova_B1s_zero + squeeze(Nova_B1s(ch,:,:,:));
end


%% 
% This part of the code shows the axial, coronal, sagittal planes of one of
% the RF shims we calculated

% CP
B1_max = abs(max(B1_est_cp, [], "all"));

figure;
Layout = tiledlayout(1, 3, 'TileSpacing', 'loose', 'Padding', 'loose');


nexttile(Layout, 1);
imagesc(squeeze(abs(B1_est_cp(round(x_dim/2),:,:)))); 
set(gca, 'XTick', [], 'YTick', []);
clim([0,B1_max])

nexttile(Layout, 2);
imagesc(squeeze(abs(B1_est_cp(:,round(y_dim/2),:)))); 
set(gca, 'XTick', [], 'YTick', []);
clim([0,B1_max])

nexttile(Layout, 3);
imagesc(squeeze(abs(B1_est_cp(:,:,round(z_dim/2))))); 
set(gca, 'XTick', [], 'YTick', []);
clim([0,B1_max])

figure;
Layout = tiledlayout(1, 3, 'TileSpacing', 'loose', 'Padding', 'loose');

nexttile(Layout, 1);
imagesc(squeeze(abs(Nova_B1s_cp(round(x_dim/2),:,:)))); 
set(gca, 'XTick', [], 'YTick', []);
clim([0,B1_max])

nexttile(Layout, 2);
imagesc(squeeze(abs(Nova_B1s_cp(:,round(y_dim/2),:)))); 
set(gca, 'XTick', [], 'YTick', []);
clim([0,B1_max])

nexttile(Layout, 3);
imagesc(squeeze(abs(Nova_B1s_cp(:,:,round(z_dim/2))))); 
set(gca, 'XTick', [], 'YTick', []);
clim([0,B1_max])


%%
% This part calculates the RMSE and the SSIM

rmse_cp = my_rmse(abs(B1_est_cp) ,abs(Nova_B1s_cp));
rmse_lm_cos = my_rmse(abs(B1_est_lm_cos) ,abs(Nova_B1s_lm_cos));
rmse_lm_sin = my_rmse(abs(B1_est_lm_sin) ,abs(Nova_B1s_lm_sin));
rmse_zero = my_rmse(abs(B1_est_zero) ,abs(Nova_B1s_zero));

disp("CP: " + string(rmse_cp))
disp("Linear 1: " + string(rmse_lm_cos))
disp("Linear 2: " + string(rmse_lm_sin))
disp("Zero Phase: " + string(rmse_zero))

max_ssim_cp = max(max(abs(B1_est_cp(:))) ,max(abs(Nova_B1s_cp(:))));
max_ssim_lm_cos = max(max(abs(B1_est_lm_cos(:))) ,max(abs(Nova_B1s_lm_cos(:))));
max_ssim_lm_sin = max(max(abs(B1_est_lm_sin(:))) ,max(abs(Nova_B1s_lm_sin(:))));
max_ssim_zero = max(max(abs(B1_est_zero(:))) ,max(abs(Nova_B1s_zero(:))));

ssim_cp = ssim(abs(B1_est_cp) ,abs(Nova_B1s_cp),'DynamicRange', max_ssim_cp);
ssim_lm_cos = ssim(abs(B1_est_lm_cos) ,abs(Nova_B1s_lm_cos),'DynamicRange', max_ssim_lm_cos);
ssim_lm_sin = ssim(abs(B1_est_lm_sin) ,abs(Nova_B1s_lm_sin),'DynamicRange', max_ssim_lm_sin);
ssim_zero = ssim(abs(B1_est_zero) ,abs(Nova_B1s_zero),'DynamicRange', max_ssim_zero);

disp("CP: " + string(ssim_cp))
disp("Linear 1: " + string(ssim_lm_cos))
disp("Linear 2: " + string(ssim_lm_sin))
disp("Zero Phase: " + string(ssim_zero))


%%
for ch = 1:8
    rmse_result = my_rmse(abs(B1_est(ch,:,:,:)) ,abs(Nova_B1s(ch,:,:,:)));
    
    disp("Channel " +string(ch) + " rmse: " + string(rmse_result))
end
%%

for ch = 1:8
    temp_B1_est = B1_est(ch,:,:,:);
    temp_Nova_B1s = Nova_B1s(ch,:,:,:);
    max_ssim_channel = max(max(abs(temp_B1_est(:))) ,max(abs(temp_Nova_B1s(:))));
    ssim_result = ssim(squeeze(abs(B1_est(ch,:,:,:))) ,squeeze(abs(Nova_B1s(ch,:,:,:))), 'DynamicRange', max_ssim_channel);
    
    disp("Channel " +string(ch) + " ssim: " + string(ssim_result))
end


%%

function [rmse] = my_rmse(simulation_pattern, experiment_pattern)
    nonzero_points = find(experiment_pattern);
    % Calculate RMSE using the magnitude
    field = (abs(experiment_pattern(:)) - abs(simulation_pattern(:))).^2;
    nonzero_field = field(nonzero_points);
    rmse = sqrt(mean(nonzero_field));
end

